/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modul3;

import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author asus
 */
public class spp extends javax.swing.JFrame {

    /**
     * Creates new form spp
     */
    public spp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jan = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        nis = new javax.swing.JTextField();
        kelas = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        feb = new javax.swing.JCheckBox();
        mar = new javax.swing.JCheckBox();
        ap = new javax.swing.JCheckBox();
        mei = new javax.swing.JCheckBox();
        jun = new javax.swing.JCheckBox();
        jul = new javax.swing.JCheckBox();
        agus = new javax.swing.JCheckBox();
        sep = new javax.swing.JCheckBox();
        ok = new javax.swing.JCheckBox();
        nov = new javax.swing.JCheckBox();
        des = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        hitung = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        totalspp = new javax.swing.JTextField();
        bayar = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jan.setForeground(new java.awt.Color(255, 255, 255));
        jan.setText("Januari");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SPPKUU");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nama");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NIS");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Kelas");

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Bulan Pembayaran");

        feb.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        feb.setForeground(new java.awt.Color(255, 255, 255));
        feb.setText("Februari");

        mar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mar.setForeground(new java.awt.Color(255, 255, 255));
        mar.setText("Maret");

        ap.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ap.setForeground(new java.awt.Color(255, 255, 255));
        ap.setText("April");

        mei.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mei.setForeground(new java.awt.Color(255, 255, 255));
        mei.setText("Mei");

        jun.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jun.setForeground(new java.awt.Color(255, 255, 255));
        jun.setText("Juni");

        jul.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jul.setForeground(new java.awt.Color(255, 255, 255));
        jul.setText("Juli");

        agus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        agus.setForeground(new java.awt.Color(255, 255, 255));
        agus.setText("Agustus");

        sep.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sep.setForeground(new java.awt.Color(255, 255, 255));
        sep.setText("September");

        ok.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ok.setForeground(new java.awt.Color(255, 255, 255));
        ok.setText("Oktober");

        nov.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nov.setForeground(new java.awt.Color(255, 255, 255));
        nov.setText("November");

        des.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        des.setForeground(new java.awt.Color(255, 255, 255));
        des.setText("Desember");

        tabel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createCompoundBorder())));
        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NAMA", "NIM", "KELAS", "BULAN", "TOTAL", "STATUS"
            }
        ));
        jScrollPane1.setViewportView(tabel);

        hitung.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hitung.setText("Hitung Total");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Total :");

        totalspp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalsppActionPerformed(evt);
            }
        });

        bayar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bayar.setText("Bayar");
        bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarActionPerformed(evt);
            }
        });

        reset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jan, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(feb, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(mar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(ap, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(mei, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jun, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jul, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(agus, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(sep, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(ok, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(nov, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(des, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(nama)
                                        .addComponent(nis)
                                        .addComponent(kelas, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)))
                                .addComponent(jLabel5)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(hitung)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(totalspp, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bayar)
                            .addComponent(reset))))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(nis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(kelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jan)
                            .addComponent(feb)
                            .addComponent(mar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ap)
                            .addComponent(mei)
                            .addComponent(jun))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jul)
                            .addComponent(agus)
                            .addComponent(sep))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ok)
                            .addComponent(nov)
                            .addComponent(des))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hitung)
                            .addComponent(jLabel6)
                            .addComponent(totalspp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(328, 328, 328)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bayar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reset)
                .addContainerGap(63, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));
        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarActionPerformed
    if (nama.getText().trim().isEmpty() || nis.getText().trim().isEmpty() || kelas.getText().trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(null, "Lengkapi Data!");
    } else {
        String namaSiswa = nama.getText().trim();
        List<String> bulanDibayar = getSelectedMonths();
        int totalSpp = bulanDibayar.size() * 100000; // Total SPP sesuai bulan yang dipilih

        if (bulanDibayar.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Pilih setidaknya satu bulan pembayaran!");
            return;
        }

        // Cek apakah siswa sudah ada di tabel
        boolean siswaSudahAda = false;
        int rowIndex = -1;

        for (int i = 0; i < mdl.getRowCount(); i++) {
            if (mdl.getValueAt(i, 0).equals(namaSiswa)) {
                siswaSudahAda = true;
                rowIndex = i;
                break;
            }
        }

        if (siswaSudahAda) {
            // Jika siswa sudah ada, tambahkan bulan baru yang belum dibayar
            String bulanLama = mdl.getValueAt(rowIndex, 3).toString();
            List<String> bulanLamaList = new ArrayList<>(List.of(bulanLama.split(" ")));

            StringBuilder bulanBaru = new StringBuilder();
            int totalBaru = 0;
            boolean adaBulanBaru = false;

            for (String bulan : bulanDibayar) {
                if (!bulanLamaList.contains(bulan)) {
                    bulanBaru.append(bulan).append(" ");
                    totalBaru += 100000; // Tambah biaya bulan baru
                    adaBulanBaru = true;
                } else {
                    // Jika bulan sudah dibayar, tampilkan pesan
                    javax.swing.JOptionPane.showMessageDialog(null, "Siswa " + namaSiswa + " sudah membayar untuk bulan " + bulan + "!");
                }
            }

            // Hapus spasi terakhir
            if (bulanBaru.length() > 0) {
                bulanBaru.setLength(bulanBaru.length() - 1);
            }

            // Jika ada bulan baru, perbarui data
            if (adaBulanBaru) {
                String bulanTotal = bulanLama + (bulanBaru.length() > 0 ? " " + bulanBaru : "");
                mdl.setValueAt(bulanTotal.trim(), rowIndex, 3); // Perbarui kolom bulan
                int totalLama = Integer.parseInt(mdl.getValueAt(rowIndex, 4).toString().replace("Rp ", "").replace(".", ""));
                mdl.setValueAt("Rp " + (totalLama + totalBaru), rowIndex, 4); // Perbarui total SPP
            }
        } else {
            // Jika siswa baru, tambahkan ke tabel
            String statusPembayaran = bulanDibayar.size() == 12 ? "Lunas" : "Nunggak";  // Status pembayaran
            mdl.addRow(new Object[]{
                nama.getText(), 
                nis.getText(), 
                kelas.getText(),                 
                String.join(" ", bulanDibayar),  // Gabungkan bulan yang dipilih
                "Rp " + totalSpp,                // Total SPP
                statusPembayaran                 // Status pembayaran
            });
        }

        tabel.setModel(mdl);
        javax.swing.JOptionPane.showMessageDialog(null, "Pembayaran Berhasil!");

        // Reset form dan checkbox
        resetForm();
        
    }                                   
}

// Metode untuk mendapatkan bulan yang dipilih
private List<String> getSelectedMonths() {
    List<String> bulanDibayar = new ArrayList<>();
    if (jan.isSelected()) bulanDibayar.add("Januari");
    if (feb.isSelected()) bulanDibayar.add("Februari");
    if (mar.isSelected()) bulanDibayar.add("Maret");
    if (ap.isSelected()) bulanDibayar.add("April");
    if (mei.isSelected()) bulanDibayar.add("Mei");
    if (jun.isSelected()) bulanDibayar.add("Juni");
    if (jul.isSelected()) bulanDibayar.add("Juli");
    if (agus.isSelected()) bulanDibayar.add("Agustus");
    if (sep.isSelected()) bulanDibayar.add("September");
    if (ok.isSelected()) bulanDibayar.add("Oktober");
    if (nov.isSelected()) bulanDibayar.add("November");
    if (des.isSelected()) bulanDibayar.add("Desember");
    return bulanDibayar;
}

// Metode untuk reset form
private void resetForm() {
    nama.setText("");
    nis.setText("");
    kelas.setText("");
    totalspp.setText("");
    jan.setSelected(false);
    feb.setSelected(false);
    mar.setSelected(false);
    ap.setSelected(false);
    mei.setSelected(false);
    jun.setSelected(false);
    jul.setSelected(false);
    agus.setSelected(false);
    sep.setSelected(false);
    ok.setSelected(false);
    nov.setSelected(false);
    des.setSelected(false);

         
    }//GEN-LAST:event_bayarActionPerformed

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
 int totalSpp = 0;
    int biayaPerBulan = 100000;

    // Cek checkbox dan tambahkan biaya jika bulan dipilih
    if (jan.isSelected()) {
        totalSpp += biayaPerBulan;
    }
    if (feb.isSelected()) {
        totalSpp += biayaPerBulan;
    }
    if (mar.isSelected()) {
        totalSpp += biayaPerBulan;
    }
    if (ap.isSelected()) {
        totalSpp += biayaPerBulan;
    }
    if (mei.isSelected()) {
        totalSpp += biayaPerBulan;
    }
    if (jun.isSelected()) {
        totalSpp += biayaPerBulan;
    }
    if (jul.isSelected()) {
        totalSpp += biayaPerBulan;
    }
    if (agus.isSelected()) {
        totalSpp += biayaPerBulan;
    }
    if (sep.isSelected()) {
        totalSpp += biayaPerBulan;
    }
    if (ok.isSelected()) {
        totalSpp += biayaPerBulan;
    }
    if (nov.isSelected()) {
        totalSpp += biayaPerBulan;
    }
    if (des.isSelected()) {
        totalSpp += biayaPerBulan;
    }

    // Tampilkan total biaya di field totalspp
    totalspp.setText("Rp " + totalSpp);
    }//GEN-LAST:event_hitungActionPerformed

    private void totalsppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalsppActionPerformed
    // TODO add your handling code here:
    }//GEN-LAST:event_totalsppActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
// Reset semua field teks (Nama, NIS, Kelas, Total SPP)
    nama.setText("");
    nis.setText("");
    kelas.setText("");
    totalspp.setText("");
    mdl.setRowCount(0);
    
// Uncheck semua checkbox bulan
    jan.setSelected(false);
    feb.setSelected(false);
    mar.setSelected(false);
    ap.setSelected(false);
    mei.setSelected(false);
    jun.setSelected(false);
    jul.setSelected(false);
    agus.setSelected(false);
    sep.setSelected(false);
    ok.setSelected(false);
    nov.setSelected(false);
    des.setSelected(false);

    // Optional: Tampilkan pesan bahwa form telah direset
    javax.swing.JOptionPane.showMessageDialog(null, "Form berhasil direset!");// TODO add your handling code here:
    }//GEN-LAST:event_resetActionPerformed

    
    
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(spp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(spp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(spp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(spp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new spp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox agus;
    private javax.swing.JCheckBox ap;
    private javax.swing.JButton bayar;
    private javax.swing.JCheckBox des;
    private javax.swing.JCheckBox feb;
    private javax.swing.JButton hitung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox jan;
    private javax.swing.JCheckBox jul;
    private javax.swing.JCheckBox jun;
    private javax.swing.JTextField kelas;
    private javax.swing.JCheckBox mar;
    private javax.swing.JCheckBox mei;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nis;
    private javax.swing.JCheckBox nov;
    private javax.swing.JCheckBox ok;
    private javax.swing.JButton reset;
    private javax.swing.JCheckBox sep;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField totalspp;
    // End of variables declaration//GEN-END:variables
int baris = 0;
static Object kolom[] = {"Nama","Nis","Kelas","Bulan","Total","Status"};
DefaultTableModel mdl = new DefaultTableModel(kolom,baris);
}
