
import java.awt.Color;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sindy
 */
public class ApotekMiniSindy extends javax.swing.JFrame { 
    
    private String[] namaObat;
    private String[] deskripsiObat;
    
    public ApotekMiniSindy() {
    initComponents();
    
    namaObat = new String[]{"Paracetamol", "Ibuprofen", "Antibiotik", "Longatin", "Antivirus",
                            "Sanadryl Ekspektoran Sirup", "Prome Sirup", "Comtusi", "Panadol 500 mg", "Procold"};
    deskripsiObat = new String[]{
                "Mengatasi demam dan nyeri ringan", //0
                "Anti-inflamasi untuk nyeri dan demam", //1
                "Antibiotik untuk infeksi bakteri", //2
                "Mengatasi gejala batuk kering pada kondisi flu dan batuk", //3
                "Obat antivirus pada kasus infeksi virus yang berat", //4
                "Mengatasi flu dan batuk berdahak", //5
                "Mengatasi batuk, terutama yang disebabkan oleh alergi", //6
                "Mengatasi flu dan batuk yang disertai batuk berdahak", //7
                "Meredakan demam dan nyeri otot yang mungkin muncul akibat flu", //8
                "Mengatasi gejala-gejala flu, seperti demam, sakit kepala, hidung tersumbat, serta batuk tidak berdahak" //9
        };
    
    }

    private void resetLabelBackground() {
        // Atur warna latar belakang label kembali ke default (biasanya putih)
        Paracetamol.setOpaque(true);
        Paracetamol.setBackground(Color.WHITE);

        Ibuprofen.setOpaque(true);
        Ibuprofen.setBackground(Color.WHITE);

        Antibiotik.setOpaque(true);
        Antibiotik.setBackground(Color.WHITE);

        Longatin.setOpaque(true);
        Longatin.setBackground(Color.WHITE);

        Antivirus.setOpaque(true);
        Antivirus.setBackground(Color.WHITE);

        Sirup.setOpaque(true);
        Sirup.setBackground(Color.WHITE);

        PromeSirup.setOpaque(true);
        PromeSirup.setBackground(Color.WHITE);

        Comtusi.setOpaque(true);
        Comtusi.setBackground(Color.WHITE);

        Panadol.setOpaque(true);
        Panadol.setBackground(Color.WHITE);

        Procold.setOpaque(true);
        Procold.setBackground(Color.WHITE);
    }

 private void tampilkanObat(String gejala, String[] namaObat, String[] deskripsiObat) {
        switch (gejala) {
            case "Pusing":
                NamaObat.setText("Nama Obat : " + namaObat[9] + ", " + namaObat[1] + " dan " + namaObat[3]);
                Deskripsi.setText("Deskripsi : " + deskripsiObat[9] + ", " + deskripsiObat[1] + " dan " + deskripsiObat[3]);
                break;
            case "Batuk":
                NamaObat.setText("Nama Obat : " + namaObat[5] + ", " + namaObat[6] + " dan " + namaObat[7]);
                Deskripsi.setText("Deskripsi : " + deskripsiObat[5] + ", " + deskripsiObat[6] + " dan " + deskripsiObat[7]);
                break;
            case "Demam":
                NamaObat.setText("Nama Obat : " + namaObat[0] + " dan " + namaObat[1]);
                Deskripsi.setText("Deskripsi : " + deskripsiObat[0] + " dan " + deskripsiObat[1]);
                break;
            case "Flu":
                NamaObat.setText("Nama Obat : " + namaObat[5] + ", " + namaObat[7] + ", " + namaObat[8] + " dan " + namaObat[9]);
                Deskripsi.setText("Deskripsi : " + deskripsiObat[5] + ", " + deskripsiObat[7] + ", " + deskripsiObat[8] + " dan " + deskripsiObat[9]);
                break;
            case "Nyeri Otot":
                NamaObat.setText("Nama Obat : " + namaObat[0] + ", " + namaObat[1] + " dan " + namaObat[8]);
                Deskripsi.setText("Deskripsi : " + deskripsiObat[0] + ", " + deskripsiObat[1] + " dan " + deskripsiObat[8]);
                break;
            default:
                NamaObat.setText("Nama Obat:... ");
                Deskripsi.setText("Deskripsi:... ");
                break;
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneltombol = new javax.swing.JPanel();
        Pusing = new javax.swing.JButton();
        Batuk = new javax.swing.JButton();
        Demam = new javax.swing.JButton();
        Flu = new javax.swing.JButton();
        Nyeriotot = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        paneldeskripsi = new javax.swing.JPanel();
        LabelGaris2 = new javax.swing.JLabel();
        NamaObat = new javax.swing.JLabel();
        Deskripsi = new javax.swing.JLabel();
        LabelGaris3 = new javax.swing.JLabel();
        panelgambar = new javax.swing.JPanel();
        Paracetamol = new javax.swing.JLabel();
        Ibuprofen = new javax.swing.JLabel();
        Antibiotik = new javax.swing.JLabel();
        Longatin = new javax.swing.JLabel();
        Antivirus = new javax.swing.JLabel();
        Sirup = new javax.swing.JLabel();
        PromeSirup = new javax.swing.JLabel();
        Comtusi = new javax.swing.JLabel();
        Panadol = new javax.swing.JLabel();
        Procold = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        paneltombol.setBackground(new java.awt.Color(204, 255, 204));
        paneltombol.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pusing.setText("Pusing");
        Pusing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PusingActionPerformed(evt);
            }
        });
        paneltombol.add(Pusing, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        Batuk.setText("Batuk");
        Batuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BatukActionPerformed(evt);
            }
        });
        paneltombol.add(Batuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));

        Demam.setText("Demam");
        Demam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DemamActionPerformed(evt);
            }
        });
        paneltombol.add(Demam, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, -1, -1));

        Flu.setText("Flu");
        Flu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FluActionPerformed(evt);
            }
        });
        paneltombol.add(Flu, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, -1, -1));

        Nyeriotot.setText("Nyeri Otot");
        Nyeriotot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NyeriototActionPerformed(evt);
            }
        });
        paneltombol.add(Nyeriotot, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setText("APOTEK MINI SINDY");
        paneltombol.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, 30));

        jLabel2.setText("Jl. Modong - Tulangan Sidoarjo Jawa Timur");
        paneltombol.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Pilihan Sakit :");
        paneltombol.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, 30));

        jLabel4.setText("--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");
        paneltombol.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, 30));

        getContentPane().add(paneltombol, java.awt.BorderLayout.PAGE_START);

        paneldeskripsi.setBackground(new java.awt.Color(255, 255, 255));
        paneldeskripsi.setLayout(new javax.swing.BoxLayout(paneldeskripsi, javax.swing.BoxLayout.PAGE_AXIS));

        LabelGaris2.setText("--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");
        paneldeskripsi.add(LabelGaris2);

        NamaObat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NamaObat.setText("Nama Obat :");
        paneldeskripsi.add(NamaObat);

        Deskripsi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Deskripsi.setText("Deskripsi :");
        paneldeskripsi.add(Deskripsi);

        LabelGaris3.setText("--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");
        paneldeskripsi.add(LabelGaris3);

        getContentPane().add(paneldeskripsi, java.awt.BorderLayout.PAGE_END);

        panelgambar.setBackground(new java.awt.Color(255, 255, 255));
        panelgambar.setLayout(new java.awt.GridLayout(2, 5));

        Paracetamol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paracetamol.png"))); // NOI18N
        Paracetamol.setText("Paracetamol");
        panelgambar.add(Paracetamol);

        Ibuprofen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ibuprofen.jpg"))); // NOI18N
        Ibuprofen.setText("Ibuprofen");
        panelgambar.add(Ibuprofen);

        Antibiotik.setIcon(new javax.swing.ImageIcon(getClass().getResource("/antibiotik.jpg"))); // NOI18N
        Antibiotik.setText("Antibiotik");
        panelgambar.add(Antibiotik);

        Longatin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/longatin.jpg"))); // NOI18N
        Longatin.setText("Longatin");
        panelgambar.add(Longatin);

        Antivirus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/antivirus.png"))); // NOI18N
        Antivirus.setText("Antivirus");
        panelgambar.add(Antivirus);

        Sirup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sanadryl Ekspektoran.png"))); // NOI18N
        Sirup.setText("Sanadryl Ekspektoran Sirup");
        panelgambar.add(Sirup);

        PromeSirup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prome sirup.png"))); // NOI18N
        PromeSirup.setText("Prome Sirup ");
        panelgambar.add(PromeSirup);

        Comtusi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/comtusi.png"))); // NOI18N
        Comtusi.setText("Comtusi");
        panelgambar.add(Comtusi);

        Panadol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panadol.png"))); // NOI18N
        Panadol.setText("Panadol 500 mg");
        panelgambar.add(Panadol);

        Procold.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proclod.png"))); // NOI18N
        Procold.setText("Procold");
        panelgambar.add(Procold);

        getContentPane().add(panelgambar, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PusingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PusingActionPerformed
        // TODO add your handling code here:
        tampilkanObat("Pusing", namaObat, deskripsiObat);
        
        resetLabelBackground();
    
        Paracetamol.setOpaque(true); // Paracetamol
        Paracetamol.setBackground(Color.YELLOW); 

        Ibuprofen.setOpaque(true); // Ibuprofen
        Ibuprofen.setBackground(Color.YELLOW);

        Longatin.setOpaque(true); // Longatin
        Longatin.setBackground(Color.YELLOW);
    }//GEN-LAST:event_PusingActionPerformed

    private void DemamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DemamActionPerformed
        // TODO add your handling code here:
        tampilkanObat("Demam", namaObat, deskripsiObat);
     
        resetLabelBackground();

        Paracetamol.setOpaque(true); // Paracetamol
        Paracetamol.setBackground(Color.ORANGE);

        Ibuprofen.setOpaque(true); // Ibuprofen
        Ibuprofen.setBackground(Color.ORANGE);
    }//GEN-LAST:event_DemamActionPerformed

    private void BatukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BatukActionPerformed
        // TODO add your handling code here:
        tampilkanObat("Batuk", namaObat, deskripsiObat);
        
        resetLabelBackground();

        Sirup.setOpaque(true); // Sanadryl Ekspektoran Sirup
        Sirup.setBackground(Color.CYAN);

        PromeSirup.setOpaque(true); // Prome Sirup
        PromeSirup.setBackground(Color.CYAN);

        Comtusi.setOpaque(true); // Comtusi
        Comtusi.setBackground(Color.CYAN);
    }//GEN-LAST:event_BatukActionPerformed

    private void FluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FluActionPerformed
        // TODO add your handling code here:
        tampilkanObat("Flu", namaObat, deskripsiObat);
        
        resetLabelBackground();

        Sirup.setOpaque(true); // Sanadryl Ekspektoran Sirup
        Sirup.setBackground(Color.PINK); 

        Comtusi.setOpaque(true); // Comtusi
        Comtusi.setBackground(Color.PINK);

        Panadol.setOpaque(true); // Panadol 500 mg
        Panadol.setBackground(Color.PINK);

        Procold.setOpaque(true); // Procold
        Procold.setBackground(Color.PINK);
    }//GEN-LAST:event_FluActionPerformed

    private void NyeriototActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NyeriototActionPerformed
        // TODO add your handling code here:
        tampilkanObat("Nyeri Otot", namaObat, deskripsiObat);
        
        resetLabelBackground();

        Paracetamol.setOpaque(true); // Paracetamol
        Paracetamol.setBackground(Color.GREEN); 

        Ibuprofen.setOpaque(true); // Ibuprofen
        Ibuprofen.setBackground(Color.GREEN);

        Panadol.setOpaque(true); // Panadol 500 mg
        Panadol.setBackground(Color.GREEN);
    }//GEN-LAST:event_NyeriototActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApotekMiniSindy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApotekMiniSindy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApotekMiniSindy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApotekMiniSindy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApotekMiniSindy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Antibiotik;
    private javax.swing.JLabel Antivirus;
    private javax.swing.JButton Batuk;
    private javax.swing.JLabel Comtusi;
    private javax.swing.JButton Demam;
    private javax.swing.JLabel Deskripsi;
    private javax.swing.JButton Flu;
    private javax.swing.JLabel Ibuprofen;
    private javax.swing.JLabel LabelGaris2;
    private javax.swing.JLabel LabelGaris3;
    private javax.swing.JLabel Longatin;
    private javax.swing.JLabel NamaObat;
    private javax.swing.JButton Nyeriotot;
    private javax.swing.JLabel Panadol;
    private javax.swing.JLabel Paracetamol;
    private javax.swing.JLabel Procold;
    private javax.swing.JLabel PromeSirup;
    private javax.swing.JButton Pusing;
    private javax.swing.JLabel Sirup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel paneldeskripsi;
    private javax.swing.JPanel panelgambar;
    private javax.swing.JPanel paneltombol;
    // End of variables declaration//GEN-END:variables

}
