/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modul5;

import Transaksi.Transaksi1;
import Transaksi.Transaksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import modul5.proyek.Proyek1;
import modul5.proyek.Proyek;
import modul5.karyawan.Karyawan1;
import modul5.karyawan.Karyawan;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;


/**
 *
 * @author Amira Alissiya
 */
public class main extends javax.swing.JFrame {
    
    public DefaultTableModel model;
    public DefaultTableModel modelP;
    public DefaultTableModel modelT;
    public Karyawan1 karyawan1 = new Karyawan1();
    public Proyek1 proyek1 = new Proyek1();
    public Transaksi1 transaksi1 = new Transaksi1();
    Connection conn;
    
    
//    Connection conn;
//    private DefaultTableModel model;
    
    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        
        conn = koneksi.getConnection();
        
        model = new DefaultTableModel(new String[]{"ID","Nama", "Jabatan", "Departemen"},0);
        modelP = new DefaultTableModel(new String[]{"ID","Nama Proyek", "Durasi Pengerjaan"},0);
        modelT = new DefaultTableModel(new String[]{"ID Karyawan","ID Proyek", "Peran"},0);
        
        loadDataKaryawan();
        loadDataProyek();
        loadDataTransaksi();

        loadComboBoxKaryawan();
        loadComboBoxProyek();
        loadDurasiProyek();
    }

    private Map<String, Integer> karyawanMap = new HashMap<>();
    private Map<String, Proyek> proyekMap = new HashMap<>();
    private Map<Integer, String> durasiMap = new HashMap<>();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableK = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jBSimpanK = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jTNamaK = new javax.swing.JTextField();
        jTJab = new javax.swing.JTextField();
        jTDep = new javax.swing.JTextField();
        jTID = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jBDelK = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableP = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jBSimpanP = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jTIDP = new javax.swing.JTextField();
        jTNamaP = new javax.swing.JTextField();
        jTDur = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableT = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jTPeran = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTIDKaryawan = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jTIDProyek = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBoxProyek = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTDurasi = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(154, 186, 221));

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 1, 24)); // NOI18N
        jLabel1.setText("Peran Karyawan dan Proyek");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(23, 23, 23))
        );

        jPanel1.setBackground(new java.awt.Color(189, 222, 245));
        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        jTableK.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "Jabatan", "Departemen"
            }
        ));
        jScrollPane2.setViewportView(jTableK);

        jPanel1.add(jScrollPane2);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jBSimpanK.setBackground(new java.awt.Color(255, 204, 204));
        jBSimpanK.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBSimpanK.setText("Tambah");
        jBSimpanK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSimpanKActionPerformed(evt);
            }
        });
        jPanel5.add(jBSimpanK, java.awt.BorderLayout.PAGE_START);

        jPanel6.setBackground(new java.awt.Color(171, 208, 243));
        jPanel6.setLayout(new java.awt.GridLayout(2, 0));

        jPanel14.setBackground(new java.awt.Color(153, 204, 255));

        jLabel16.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel16.setText("Departemen :");

        jLabel17.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel17.setText("ID :");

        jLabel18.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel18.setText("Nama Karyawan :");

        jLabel19.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel19.setText("Jabatan :");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTJab, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTDep, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel17))
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel18)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTNamaK, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTID, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTNamaK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTJab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jTDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel14);

        jPanel15.setBackground(new java.awt.Color(186, 220, 253));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jBDelK.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBDelK.setText("Delete");
        jBDelK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDelKActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jBDelK, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jBDelK))
                .addGap(37, 37, 37)
                .addComponent(jButton3)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel15);

        jPanel5.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel5);

        jTabbedPane1.addTab("Karyawan", jPanel1);

        jPanel2.setLayout(new java.awt.GridLayout(2, 0));

        jTableP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nama Proyek", "Durasi Pengerjaan"
            }
        ));
        jScrollPane1.setViewportView(jTableP);

        jPanel2.add(jScrollPane1);

        jPanel7.setBackground(new java.awt.Color(212, 230, 247));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jBSimpanP.setBackground(new java.awt.Color(255, 204, 204));
        jBSimpanP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBSimpanP.setText("Tambah");
        jBSimpanP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSimpanPActionPerformed(evt);
            }
        });
        jPanel7.add(jBSimpanP, java.awt.BorderLayout.PAGE_START);

        jPanel18.setLayout(new java.awt.GridLayout(2, 0));

        jPanel19.setBackground(new java.awt.Color(193, 222, 250));

        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel13.setText("ID :");

        jLabel14.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel14.setText("Nama Proyek :");

        jLabel15.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel15.setText("Durasi Pengerjaan :");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTNamaP, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTIDP, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jTDur, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTIDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTNamaP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)))
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTDur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel18.add(jPanel19);

        jPanel20.setBackground(new java.awt.Color(211, 236, 249));

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setText("Edit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton6.setText("Delete");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setText("Reset");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton4))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel18.add(jPanel20);

        jPanel7.add(jPanel18, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel7);

        jTabbedPane1.addTab("Proyek", jPanel2);

        jPanel3.setLayout(new java.awt.GridLayout(1, 2));

        jTableT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Karyawan", "ID Proyek", "Peran"
            }
        ));
        jScrollPane3.setViewportView(jTableT);

        jPanel3.add(jScrollPane3);

        jPanel9.setBackground(new java.awt.Color(235, 203, 211));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jButton7.setBackground(new java.awt.Color(255, 204, 204));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton7.setText("Tambah");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton7, java.awt.BorderLayout.PAGE_START);

        jPanel10.setBackground(new java.awt.Color(235, 203, 211));
        jPanel10.setLayout(new java.awt.GridLayout(2, 0));

        jPanel11.setBackground(new java.awt.Color(255, 204, 204));
        jPanel11.setLayout(new java.awt.BorderLayout());

        jPanel13.setBackground(new java.awt.Color(169, 212, 255));

        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton8.setText("Edit");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton9.setText("Delete");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel11.setText("Peran :");

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel12.setText("ID Karyawan :");

        jButton10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton10.setText("Reset");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel20.setText("ID Proyek :");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                        .addComponent(jTPeran, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jTIDKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(jTIDProyek, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTIDKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTIDProyek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTPeran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(28, 28, 28)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton9)
                    .addComponent(jButton10))
                .addGap(28, 28, 28))
        );

        jPanel11.add(jPanel13, java.awt.BorderLayout.CENTER);

        jPanel10.add(jPanel11);

        jPanel12.setBackground(new java.awt.Color(195, 219, 242));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel7.setText("Karyawan :");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBoxProyek.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        jComboBoxProyek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProyekActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel9.setText("Proyek :");

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel10.setText("Durasi :");

        jTDurasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTDurasiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jComboBoxProyek, javax.swing.GroupLayout.Alignment.LEADING, 0, 181, Short.MAX_VALUE)
                    .addComponent(jTDurasi, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxProyek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTDurasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jPanel10.add(jPanel12);

        jPanel9.add(jPanel10, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel9);

        jTabbedPane1.addTab("Transaksi Proyek", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 791, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        String peran = jTPeran.getText();
        String namaKaryawan = (String) jComboBox1.getSelectedItem();
        String namaProyek = (String) jComboBoxProyek.getSelectedItem();
        
        if (jTPeran.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Isi Form Terlebih Dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        jTPeran.setText("");
        jTIDKaryawan.requestFocus();
        return;
        }

        // Dapatkan ID karyawan dan proyek dari Map
        int idKaryawan = karyawanMap.getOrDefault(namaKaryawan, -1);
        Proyek proyek = proyekMap.get(namaProyek); // Dapatkan objek Proyek berdasarkan namaProyek
        int idProyek = (proyek != null) ? proyek.getId() : -1; // Jika proyek tidak null, ambil id; jika null, gunakan -1

        // Validasi ID karyawan dan proyek
        if (idKaryawan == -1 || idProyek == -1) {
            System.out.println("Karyawan atau proyek tidak valid");
            return;
        }

        // Buat objek Transaksi dengan ID yang valid
        Transaksi trs = new Transaksi(idKaryawan, idProyek, peran);

        try {
            transaksi1.insertTransaksi(trs);
            loadDataTransaksi();
            JOptionPane.showMessageDialog(this, "Data Berhasil Disimpan");
            jTIDKaryawan.setText("");
            jTPeran.setText("");
            return;
            
        } catch (SQLException e) {
            System.out.println("Tidak dapat menambahkan transaksi, error: " + e);
        }

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jBSimpanKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSimpanKActionPerformed
        // TODO add your handling code here:
        String ID = jTID.getText();
        String NamaK = jTNamaK.getText();
        String Jab = jTJab.getText();
        String Dep = jTDep.getText();
        
        Karyawan kry = new Karyawan(
         0,
         NamaK,
         Jab,
         Dep
         );
        
        if (jTNamaK.getText().isEmpty() || jTJab.getText().isEmpty() || jTDep.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Isi Form Terlebih Dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        jTNamaK.setText("");
        jTJab.setText("");
        jTDep.setText("");
        jTNamaK.requestFocus();
        return;
        }
        
        try{
            karyawan1.insertKaryawan(kry);
            loadDataKaryawan();
            JOptionPane.showMessageDialog(this, "Data Berhasil Disimpan");
            jTNamaK.setText("");
            jTJab.setText("");
            jTDep.setText("");
            jTNamaK.requestFocus();
            return;

        } catch (SQLException e){
            System.out.println("Tidak dapat menambahkan karyawan, error: " +e);
        }
    }//GEN-LAST:event_jBSimpanKActionPerformed

    private void jBSimpanPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSimpanPActionPerformed
        // TODO add your handling code here:
        String ID = jTIDP.getText();
        String NamaP = jTNamaP.getText();
        String Durasi = jTDur.getText();
        
        Proyek pry = new Proyek(
         0,
         NamaP,
         Durasi
         );
        
        if (jTNamaP.getText().isEmpty() || jTDur.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Isi Form Terlebih Dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        jTNamaP.setText("");
        jTDur.setText("");
        jTNamaP.requestFocus();
        return;
        }
        
        try{
            proyek1.insertProyek(pry);
            loadDataProyek();
            JOptionPane.showMessageDialog(this, "Data Berhasil Disimpan");
            jTNamaP.setText("");
            jTDur.setText("");
            return;
        } catch (SQLException e){
            System.out.println("Tidak dapat menambahkan proyek, error: " +e);
        }        
    }//GEN-LAST:event_jBSimpanPActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        updateDataK();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        updateDataP();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        updateDataT();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jBDelKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDelKActionPerformed
        // TODO add your handling code here:
        int delete = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin mengapus data?", 
        "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if (delete == JOptionPane.YES_OPTION) {
            try {
            if (jTID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Isi ID Terlebih Dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            jTID.setText("");
            jTID.requestFocus();
            return;
            }
            
            int idKaryawan = Integer.parseInt(jTID.getText());
            
            // Hapus data terkait di tabel transaksi
            String sqlTransaksi = "DELETE FROM transaksi WHERE id_karyawan = ?";
            PreparedStatement stmtTransaksi = conn.prepareStatement(sqlTransaksi);
            stmtTransaksi.setInt(1, idKaryawan);
            stmtTransaksi.executeUpdate();

            // Hapus data di tabel karyawan
            String sqlKaryawan = "DELETE FROM karyawan WHERE id_karyawan = ?";
            PreparedStatement stmtKaryawan = conn.prepareStatement(sqlKaryawan);
            stmtKaryawan.setInt(1, idKaryawan);
            stmtKaryawan.executeUpdate();

            JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus");
            loadDataKaryawan();
            jTNamaK.setText("");
            jTJab.setText("");
            jTDep.setText("");
            jTID.setText(""); 
            return;
        } catch (SQLException e) {
            System.out.println("Error Delete Data: " + e.getMessage());
        }
            
        } else{
            return;
        }
           
    }//GEN-LAST:event_jBDelKActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int delete = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin mengapus data?", 
        "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if (delete == JOptionPane.YES_OPTION) {
        try {
            int idProyek = Integer.parseInt(jTIDP.getText());

            // Hapus data terkait di tabel transaksi
            String sqlTransaksi = "DELETE FROM transaksi WHERE id_proyek = ?";
            PreparedStatement stmtTransaksi = conn.prepareStatement(sqlTransaksi);
            stmtTransaksi.setInt(1, idProyek);
            stmtTransaksi.executeUpdate();

            // Hapus data di tabel karyawan
            String sqlKaryawan = "DELETE FROM proyek WHERE id_proyek = ?";
            PreparedStatement stmtKaryawan = conn.prepareStatement(sqlKaryawan);
            stmtKaryawan.setInt(1, idProyek);
            stmtKaryawan.executeUpdate();

            JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus");
            loadDataProyek();
            
        } catch (SQLException e) {
            System.out.println("Error Delete Data: " + e.getMessage());
        }
        } else{
            return;
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        int delete = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin mengapus data?", 
        "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if (delete == JOptionPane.YES_OPTION) {
        try {
            if (jTIDKaryawan.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Isi Form Terlebih Dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            jTPeran.setText("");
            jTIDKaryawan.setText("");
            jTIDKaryawan.requestFocus();
            return;
            }
                    
            int idT = Integer.parseInt(jTIDKaryawan.getText());

            // Hapus data terkait di tabel transaksi
            String sqlTransaksi = "DELETE FROM transaksi WHERE id_karyawan = ?";
            PreparedStatement stmtTransaksi = conn.prepareStatement(sqlTransaksi);
            stmtTransaksi.setInt(1, idT);
            stmtTransaksi.executeUpdate();

            JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus");
            loadDataTransaksi();
            jTIDKaryawan.setText("");
            jTPeran.setText("");
            return;
        } catch (SQLException e) {
            System.out.println("Error Delete Data: " + e.getMessage());
        }
        } else{
            return;
        }
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jComboBoxProyekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProyekActionPerformed
        // TODO add your handling code here:
        String namaProyek = (String) jComboBoxProyek.getSelectedItem();
        Proyek selectedProyek = proyekMap.get(namaProyek);

        if (selectedProyek != null) {
            jTDurasi.setText(selectedProyek.getDurasi_pengerjaan() + " minggu");
        }
    }//GEN-LAST:event_jComboBoxProyekActionPerformed

    private void jTDurasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTDurasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTDurasiActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int reset = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin mereset data?", 
        "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if (reset == JOptionPane.YES_OPTION) {
        jTNamaK.setText("");
        jTJab.setText("");
        jTDep.setText("");
        jTID.setText("");  
        } else{
            return;
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int reset = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin mereset data?", 
        "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if (reset == JOptionPane.YES_OPTION) {
        jTNamaP.setText("");
        jTDur.setText("");
        jTIDP.setText("");
        } else{
            return;
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        int reset = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin mereset data?", 
        "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if (reset == JOptionPane.YES_OPTION) {
        jTIDKaryawan.setText("");
        jTPeran.setText("");
        } else{
            return;
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    public void loadDataKaryawan(){
        model.setRowCount(0);
        
        try{
            List<Karyawan> list_karyawan = karyawan1.getAllKaryawan();
            for (Karyawan kry : list_karyawan){
                model.addRow(
                        new Object[]{
                           kry.getId(),
                           kry.getNamaK(),
                           kry.getJab(),
                           kry.getDep()
                        }
                );
            }
            jTableK.setModel(model);

        } catch (SQLException e){
            System.out.println("Tidak dapat memuat data, error" + e);
        }
    }
    
    
    public void loadDataProyek(){
        modelP.setRowCount(0);
        
        try{
            List<Proyek> list_proyek = proyek1.getAllProyek();
            for (Proyek pry : list_proyek){
                modelP.addRow(
                        new Object[]{
                           pry.getId(),
                           pry.getNama_proyek(),
                           pry.getDurasi_pengerjaan()
                        }
                );
            }
            jTableP.setModel(modelP);
            
        } catch (SQLException e){
            System.out.println("Tidak dapat memuat data, error" + e);
        }
    }
        
    public void loadDataTransaksi(){
        modelT.setRowCount(0);
        loadDataProyek();
        loadDataKaryawan();
        
        try{
            List<Transaksi> list_transaksi = transaksi1.getAllTransaksi();
            for (Transaksi trs : list_transaksi){
                modelT.addRow(
                        new Object[]{
                           trs.getId_karyawan(),
                           trs.getId_proyek(),
                           trs.getPeran()
                        }
                );
            }
            jTableT.setModel(modelT);
        } catch (SQLException e){
            System.out.println("Tidak dapat memuat data, error" + e);
        }
    }
        
        
    private void updateDataK() {
        try {           
            if (jTNamaK.getText().isEmpty() || jTJab.getText().isEmpty() || jTDep.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Isi Form Terlebih Dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            jTNamaK.setText("");
            jTJab.setText("");
            jTDep.setText("");
            jTID.requestFocus();
            return;
            }
            
             List<Karyawan> list_karyawan = karyawan1.getAllKaryawan();
            int idK = Integer.parseInt(jTID.getText());

            boolean found = false;

            for (Karyawan karyawan : list_karyawan) {
                if (karyawan.getId()== idK) {
                    found = true;
                    break;
                }
            }

            if (!found) {
                JOptionPane.showMessageDialog(this, "Data tidak ada di tabel.");
            }else if (found=true){
            String sql = "UPDATE karyawan SET nama = ?, jabatan=?, departemen =? WHERE id_karyawan = ?";
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, jTNamaK.getText());
            stmt.setString(2, jTJab.getText());
            stmt.setString(3, jTDep.getText());
            stmt.setInt(4, Integer.parseInt(jTID.getText()));
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data Berhasil Diupdate");
       
            jTNamaK.setText("");
            jTJab.setText("");
            jTDep.setText("");
            jTID.setText("");
            loadDataKaryawan();
            return;
            }        
        }  catch (SQLException e) {
            System.out.println("Error Save Data" + e.getMessage());
        }
   }
    
    private void updateDataP() {
        try {
            if (jTNamaP.getText().isEmpty() || jTDur.getText().isEmpty() || jTIDP.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Isi Form Terlebih Dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            jTNamaP.setText("");
            jTDur.setText("");
            jTIDP.setText("");
            jTIDP.requestFocus();
            return;
            }
            
            List<Proyek> list_proyek = proyek1.getAllProyek();
            int idP = Integer.parseInt(jTIDP.getText());

            boolean found = false;

            for (Proyek proyek : list_proyek) {
                if (proyek.getId()== idP) {
                    found = true;
                    break;
                }
            }

            if (!found) {
                JOptionPane.showMessageDialog(this, "Data tidak ada di tabel.");
            }else if (found=true){

                String sql = "UPDATE proyek SET nama_proyek = ?, durasi_pengerjaan=? WHERE id_proyek = ?";
                PreparedStatement stmt = conn.prepareStatement(sql);
                stmt.setString(1, jTNamaP.getText());
                stmt.setString(2, jTDur.getText());
                stmt.setInt(3, Integer.parseInt(jTIDP.getText()));
                stmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data Berhasil Diupdate");

                jTIDP.setText("");
                jTNamaP.setText("");
                jTDur.setText("");
                return;
            }
            }  catch (SQLException e) {
                System.out.println("Error Save Data" + e.getMessage());
            }
   }
        
    private void updateDataT() {
        try {
            if (jTPeran.getText().isEmpty() || jTIDKaryawan.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Isi Form Terlebih Dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            jTPeran.setText("");
            jTIDKaryawan.setText("");
            jTIDProyek.setText("");
            jTIDKaryawan.requestFocus();
            return;
            }
            
        List<Transaksi> list_transaksi = transaksi1.getAllTransaksi();
        int idK = Integer.parseInt(jTIDKaryawan.getText());
        int idP = Integer.parseInt(jTIDProyek.getText());

        boolean found = false;

        for (Transaksi transaksi : list_transaksi) {
            if (transaksi.getId_karyawan() == idK && transaksi.getId_proyek() == idP) {
                found = true;
                break;
            }
        }

        if (!found) {
            JOptionPane.showMessageDialog(this, "Data tidak ada di tabel.");
        }else if (found=true){
            String sql = "UPDATE transaksi SET peran = ? WHERE id_karyawan = ? AND id_proyek=?";
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, jTPeran.getText());
            stmt.setInt(2, Integer.parseInt(jTIDKaryawan.getText()));
            stmt.setInt(3, Integer.parseInt(jTIDProyek.getText()));
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data Berhasil Diupdate");
        
            jTIDKaryawan.setText("");
            jTIDProyek.setText("");
            jTPeran.setText("");
            loadDataTransaksi();
            return; 
        }

        }  catch (SQLException e) {
            System.out.println("Error Save Data" + e.getMessage());
        }
   }
        
        
    public void loadComboBoxKaryawan() {
        loadDataKaryawan();
        jComboBox1.removeAllItems();
        karyawanMap.clear();
        try {
            List<Karyawan> listKaryawan = karyawan1.getAllKaryawan();
            for (Karyawan karyawan : listKaryawan) {
                String nama = karyawan.getNamaK();
                int id = karyawan.getId();
                String item = id + " - " + nama;
                karyawanMap.put(item, id);
                jComboBox1.addItem(item);
            }
        } catch (SQLException e) {
            System.out.println("Tidak dapat memuat nama karyawan, error: " + e);
        }
    }
    

    public void loadComboBoxProyek() {
        jComboBoxProyek.removeAllItems();
        proyekMap.clear();
        try {
            List<Proyek> listProyek = proyek1.getAllProyek();
            for (Proyek proyek : listProyek) {
                String nama = proyek.getNama_proyek();
                int id = proyek.getId();
                String item = id + " - " + nama;
                proyekMap.put(item, proyek); // Masukkan objek Proyek ke dalam proyekMap
                jComboBoxProyek.addItem(item); // Tambahkan nama proyek ke ComboBox
            }
        } catch (SQLException e) {
            System.out.println("Tidak dapat memuat nama proyek, error: " + e);
        }
    }

    
    public void loadDurasiProyek() {
        durasiMap.clear();
        try {
            List<Proyek> listProyek = proyek1.getAllProyek();
            for (Proyek proyek : listProyek) {
                int id = proyek.getId();
                String durasi = proyek.getDurasi_pengerjaan();
                durasiMap.put(id, durasi);
            }
        } catch (SQLException e) {
            System.out.println("Tidak dapat memuat durasi proyek, error: " + e);
        }
    }            
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBDelK;
    private javax.swing.JButton jBSimpanK;
    private javax.swing.JButton jBSimpanP;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBoxProyek;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTDep;
    private javax.swing.JTextField jTDur;
    private javax.swing.JTextField jTDurasi;
    private javax.swing.JTextField jTID;
    private javax.swing.JTextField jTIDKaryawan;
    private javax.swing.JTextField jTIDP;
    private javax.swing.JTextField jTIDProyek;
    private javax.swing.JTextField jTJab;
    private javax.swing.JTextField jTNamaK;
    private javax.swing.JTextField jTNamaP;
    private javax.swing.JTextField jTPeran;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableK;
    private javax.swing.JTable jTableP;
    private javax.swing.JTable jTableT;
    // End of variables declaration//GEN-END:variables
}
