
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class UTS extends javax.swing.JFrame {

    /**
     * Creates new form UTS
     */
    public UTS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btsuit = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        blkiri = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        rbbatu = new javax.swing.JRadioButton();
        rbgunting = new javax.swing.JRadioButton();
        rbkertas = new javax.swing.JRadioButton();
        blatas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        blbawah = new javax.swing.JPanel();
        btmain = new javax.swing.JButton();
        btreset = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        blkanan = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfkomputer = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfuser = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        blkiri.setBackground(new java.awt.Color(210, 182, 147));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Masukkan pilihan anda");

        btsuit.add(rbbatu);
        rbbatu.setText("Batu");

        btsuit.add(rbgunting);
        rbgunting.setText("Gunting");

        btsuit.add(rbkertas);
        rbkertas.setText("Kertas");

        javax.swing.GroupLayout blkiriLayout = new javax.swing.GroupLayout(blkiri);
        blkiri.setLayout(blkiriLayout);
        blkiriLayout.setHorizontalGroup(
            blkiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blkiriLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(blkiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, blkiriLayout.createSequentialGroup()
                        .addComponent(rbkertas)
                        .addContainerGap(206, Short.MAX_VALUE))
                    .addGroup(blkiriLayout.createSequentialGroup()
                        .addGroup(blkiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbbatu)
                            .addComponent(jLabel2)
                            .addComponent(rbgunting))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        blkiriLayout.setVerticalGroup(
            blkiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blkiriLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(rbbatu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbgunting)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbkertas)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jPanel1.add(blkiri, java.awt.BorderLayout.CENTER);

        blatas.setBackground(new java.awt.Color(162, 127, 75));

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("GAME SUIT");

        javax.swing.GroupLayout blatasLayout = new javax.swing.GroupLayout(blatas);
        blatas.setLayout(blatasLayout);
        blatasLayout.setHorizontalGroup(
            blatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, blatasLayout.createSequentialGroup()
                .addContainerGap(144, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(139, 139, 139))
        );
        blatasLayout.setVerticalGroup(
            blatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blatasLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel1.add(blatas, java.awt.BorderLayout.PAGE_START);

        blbawah.setBackground(new java.awt.Color(209, 181, 148));

        btmain.setText("MAIN");
        btmain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmainActionPerformed(evt);
            }
        });

        btreset.setText("reset");
        btreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btresetActionPerformed(evt);
            }
        });

        jButton2.setText("Keluar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout blbawahLayout = new javax.swing.GroupLayout(blbawah);
        blbawah.setLayout(blbawahLayout);
        blbawahLayout.setHorizontalGroup(
            blbawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blbawahLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btmain, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(btreset, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        blbawahLayout.setVerticalGroup(
            blbawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, blbawahLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(blbawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btmain, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btreset, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        jPanel1.add(blbawah, java.awt.BorderLayout.PAGE_END);

        blkanan.setBackground(new java.awt.Color(209, 181, 148));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Komputer");

        tfkomputer.setEditable(false);

        jLabel4.setText("User");

        tfuser.setEditable(false);
        tfuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfuserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout blkananLayout = new javax.swing.GroupLayout(blkanan);
        blkanan.setLayout(blkananLayout);
        blkananLayout.setHorizontalGroup(
            blkananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blkananLayout.createSequentialGroup()
                .addGroup(blkananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(blkananLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3))
                    .addGroup(blkananLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(blkananLayout.createSequentialGroup()
                .addGroup(blkananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfkomputer, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfuser, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 84, Short.MAX_VALUE))
        );
        blkananLayout.setVerticalGroup(
            blkananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blkananLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(tfkomputer, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfuser, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel1.add(blkanan, java.awt.BorderLayout.LINE_END);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btmainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmainActionPerformed
        // TODO add your handling code here:
        String pilih = "";
        if (rbbatu.isSelected()){
            pilih ="batu";
        }else if (rbgunting.isSelected()){
            pilih = "gunting";
        }else if (rbkertas.isSelected()){
            pilih = "kertas";
        }
        
        tfuser.setText(pilih);
        
        if(pilih  == "batu" ){
            tfkomputer.setText("kertas");
            JOptionPane.showMessageDialog(this, "anda kalah");
        }else if (pilih  == "kertas"){
            tfkomputer.setText("batu");
            JOptionPane.showMessageDialog(this, "selamat anda menang");
        }else if (pilih  == "gunting"){
            tfkomputer.setText("kertas");
            JOptionPane.showMessageDialog(this, "selamat anda menang");
        }
    }//GEN-LAST:event_btmainActionPerformed

    private void btresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btresetActionPerformed
        // TODO add your handling code here:
            tfkomputer.setText("");
            tfuser.setText("");
            btsuit.clearSelection();
        
    }//GEN-LAST:event_btresetActionPerformed

    private void tfuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfuserActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UTS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel blatas;
    private javax.swing.JPanel blbawah;
    private javax.swing.JPanel blkanan;
    private javax.swing.JPanel blkiri;
    private javax.swing.JButton btmain;
    private javax.swing.JButton btreset;
    private javax.swing.ButtonGroup btsuit;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbbatu;
    private javax.swing.JRadioButton rbgunting;
    private javax.swing.JRadioButton rbkertas;
    private javax.swing.JTextField tfkomputer;
    private javax.swing.JTextField tfuser;
    // End of variables declaration//GEN-END:variables
}
