/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg230441100169_firliana.eka.kurnia.sari_modul3;

/**
 *
 * @author ASUS
 */
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
public class Apotekk extends javax.swing.JFrame {
    private JCheckBox[] obatCheckboxes;
   
private final String[][] daftarObat = {
            {"CoughSyrup", "Rp 39.000", "Digunakan untuk meredakan batuk."},
            {"Paracetamol", "Rp 5.000", "Meredakan sakit ringan, sakit kepala, panas."},
            {"Ibuprofen", "Rp 6.000", "Meredakan sakit kepala, sakit gigi."},
            {"PseudoePhedrine", "Rp 8.000", "Meringankan gejala flu."},
            {"Antasida", "Rp 7.000", "Obat untuk mengurangi nyeri lambung."},
            {"CoughDrops", "Rp 36.000", "Digunakan untuk meredakan gatal pada tenggorokan."},
            {"PainReliefCream", "Rp 37.000", "cream untuk meredakan nyeri otot."},
            {"Omeprazole", "Rp 10.000", "Mengobati asam lambung."},
            {"HeadacheRelief", "Rp 25.000", "Menghilangkan sakit kepala / migrain."},
            {"Theraflu", "Rp 50.000", "Mengobati flu biasa, alergi, penyakit pernapasan."}
    };
private Iterable<JCheckBox> obatCheckBoxes;

    
    public Apotekk() {
        initComponents();
        
        obatCheckboxes = new JCheckBox[]{
            cbCoughSyrup, cbParacetamol, cbIbuprofen, cbPseudoephedrine, cbAntasida, 
            cbCoughDrops, cbPainReliefCream, cbOmeprazole, cbHeadacherelief, cbTheraflu
        };
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbCoughSyrup = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        cbParacetamol = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        cbIbuprofen = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        cbPseudoephedrine = new javax.swing.JCheckBox();
        jLabel15 = new javax.swing.JLabel();
        cbOmeprazole = new javax.swing.JCheckBox();
        jLabel18 = new javax.swing.JLabel();
        cbAntasida = new javax.swing.JCheckBox();
        jLabel16 = new javax.swing.JLabel();
        cbCoughDrops = new javax.swing.JCheckBox();
        jLabel17 = new javax.swing.JLabel();
        cbPainReliefCream = new javax.swing.JCheckBox();
        jLabel20 = new javax.swing.JLabel();
        cbHeadacherelief = new javax.swing.JCheckBox();
        jLabel19 = new javax.swing.JLabel();
        cbTheraflu = new javax.swing.JCheckBox();
        show = new javax.swing.JButton();
        DetailObat = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        pesan = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        taDetailObat = new javax.swing.JTextArea();
        namaObat1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfharga = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfnamaobat = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfjumlah = new javax.swing.JTextField();
        total = new javax.swing.JButton();
        clear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\download-removebg-preview.png")); // NOI18N
        jPanel2.add(jLabel1, java.awt.BorderLayout.LINE_START);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("                          Apotek Medika 24 Jam");
        jPanel2.add(jLabel2, java.awt.BorderLayout.CENTER);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("                                                                 Jl. Kusuma Dharma, Denpasar-Bali");
        jPanel2.add(jLabel3, java.awt.BorderLayout.PAGE_END);

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));

        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("                                                          Pilihan Obat :");
        jPanel4.add(jLabel4);

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\download__4_-removebg-preview.png")); // NOI18N

        buttonGroup1.add(cbCoughSyrup);
        cbCoughSyrup.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbCoughSyrup.setText("Cough Syrup");
        cbCoughSyrup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCoughSyrupActionPerformed(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\download__5_-removebg-preview.png")); // NOI18N

        buttonGroup1.add(cbParacetamol);
        cbParacetamol.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbParacetamol.setText("Paracetamol");

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\download__6_-removebg-preview.png")); // NOI18N

        buttonGroup1.add(cbIbuprofen);
        cbIbuprofen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbIbuprofen.setText("Ibu Profen");

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\download__7_-removebg-preview.png")); // NOI18N

        buttonGroup1.add(cbPseudoephedrine);
        cbPseudoephedrine.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbPseudoephedrine.setText("PseudoePhedrine");

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\download__8_-removebg-preview.png")); // NOI18N

        buttonGroup1.add(cbOmeprazole);
        cbOmeprazole.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbOmeprazole.setText("Omeprazole");

        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\download__9_-removebg-preview.png")); // NOI18N

        buttonGroup1.add(cbAntasida);
        cbAntasida.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbAntasida.setText("Antasida");

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\download__10_-removebg-preview.png")); // NOI18N

        buttonGroup1.add(cbCoughDrops);
        cbCoughDrops.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbCoughDrops.setText("Cough Droups");

        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\download__11_-removebg-preview.png")); // NOI18N

        buttonGroup1.add(cbPainReliefCream);
        cbPainReliefCream.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbPainReliefCream.setText("Pain Relief Cream");

        jLabel20.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\download__12_-removebg-preview.png")); // NOI18N

        buttonGroup1.add(cbHeadacherelief);
        cbHeadacherelief.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbHeadacherelief.setText("Headache Relief");

        jLabel19.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\download__13_-removebg-preview.png")); // NOI18N

        buttonGroup1.add(cbTheraflu);
        cbTheraflu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbTheraflu.setText("Theraflu");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(cbCoughSyrup)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cbParacetamol)
                        .addGap(18, 18, 18)
                        .addComponent(cbIbuprofen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbPseudoephedrine))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17)
                        .addGap(14, 14, 14))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(cbAntasida)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cbHeadacherelief)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbTheraflu, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbOmeprazole)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbCoughDrops)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbPainReliefCream))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel19)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbCoughSyrup))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel14))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(cbParacetamol)
                                            .addComponent(cbIbuprofen)
                                            .addComponent(cbPseudoephedrine))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel15)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbOmeprazole)
                            .addComponent(cbAntasida)
                            .addComponent(cbCoughDrops)
                            .addComponent(cbPainReliefCream))
                        .addGap(28, 28, 28)
                        .addComponent(jLabel20))
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbHeadacherelief)
                    .addComponent(cbTheraflu))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        show.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        show.setText("Show");
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });

        DetailObat.setLayout(new javax.swing.BoxLayout(DetailObat, javax.swing.BoxLayout.LINE_AXIS));

        jPanel5.setBackground(new java.awt.Color(255, 204, 204));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pesan.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        pesan.setText("Pesan obat :");
        jPanel5.add(pesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        taDetailObat.setColumns(20);
        taDetailObat.setRows(5);
        jScrollPane3.setViewportView(taDetailObat);

        jPanel5.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 230, 130));

        namaObat1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        namaObat1.setText("Detail Obat :");
        jPanel5.add(namaObat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("Harga :");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));
        jPanel5.add(tfharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 140, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("Nama Obat :");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));
        jPanel5.add(tfnamaobat, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 140, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("Jumlah Pesan :");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));
        jPanel5.add(tfjumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 140, -1));

        total.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        total.setText("Total");
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });
        jPanel5.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        DetailObat.add(jPanel5);

        clear.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DetailObat, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(show)
                .addGap(94, 94, 94))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(630, Short.MAX_VALUE)
                    .addComponent(clear)
                    .addGap(5, 5, 5)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DetailObat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(show)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(515, Short.MAX_VALUE)
                    .addComponent(clear)
                    .addGap(5, 5, 5)))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < obatCheckboxes.length; i++) {
            if (obatCheckboxes[i].isSelected()) {
                sb.append("Nama Obat: ").append(daftarObat[i][0]).append("\n")
                  .append("Harga: ").append(daftarObat[i][1]).append("\n")
                  .append("Keterangan: ").append(daftarObat[i][2]).append("\n\n");
            }
        }
        taDetailObat.setText(sb.toString());
     // TODO add your handling code here:
    }//GEN-LAST:event_showActionPerformed
     // Jika tidak ada yang dipilih

    private void cbCoughSyrupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCoughSyrupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCoughSyrupActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
       taDetailObat.setText("");
       buttonGroup1.clearSelection();
       tfnamaobat.setText("");
       tfjumlah.setText("");
       tfharga.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_clearActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        try {
            String namaObat = tfnamaobat.getText();
            int jumlahPesan = Integer.parseInt(tfjumlah.getText());
            int hargaPerUnit = Integer.parseInt(tfharga.getText());

            // Menghitung total
            int totalHarga = jumlahPesan * hargaPerUnit;

            // Menampilkan hasil dalam JOptionPane (dialog)
            String pesanHasil = "Nama Obat: " + namaObat + "\n" +
                                "Jumlah: " + jumlahPesan + "\n" +
                                "Total Harga: Rp " + totalHarga;

            JOptionPane.showMessageDialog(this, pesanHasil, "Hasil Perhitungan", JOptionPane.INFORMATION_MESSAGE);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Input tidak valid. Pastikan jumlah pesan dan harga per unit adalah angka.", "Error", JOptionPane.ERROR_MESSAGE);
        }       // TODO add your handling code here:
    }//GEN-LAST:event_totalActionPerformed

    /**
     * @param args the command line arguments 
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Apotekk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Apotekk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Apotekk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Apotekk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Apotekk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DetailObat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbAntasida;
    private javax.swing.JCheckBox cbCoughDrops;
    private javax.swing.JCheckBox cbCoughSyrup;
    private javax.swing.JCheckBox cbHeadacherelief;
    private javax.swing.JCheckBox cbIbuprofen;
    private javax.swing.JCheckBox cbOmeprazole;
    private javax.swing.JCheckBox cbPainReliefCream;
    private javax.swing.JCheckBox cbParacetamol;
    private javax.swing.JCheckBox cbPseudoephedrine;
    private javax.swing.JCheckBox cbTheraflu;
    private javax.swing.JButton clear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel namaObat1;
    private javax.swing.JLabel pesan;
    private javax.swing.JButton show;
    private javax.swing.JTextArea taDetailObat;
    private javax.swing.JTextField tfharga;
    private javax.swing.JTextField tfjumlah;
    private javax.swing.JTextField tfnamaobat;
    private javax.swing.JButton total;
    // End of variables declaration//GEN-END:variables

    

}


