/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BayarSPP;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel ;

/**
 *
 * @author sindy
 */
public class SiswaSindy extends javax.swing.JFrame {

    /**
     * Creates new form SiswaSindy
     */
    
    private DefaultTableModel modelTabel;
    private boolean[] bulan = new boolean[12]; 
    int total = 0;
    public SiswaSindy() {
        
    initComponents(); 
    initTableModel();
    
    }
    
    private void initTableModel() {
    modelTabel = new DefaultTableModel(new String[]{"Nama Siswa", "Bulan", "Jumlah SPP"}, 0);
    TabelRiwayat.setModel(modelTabel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        North = new javax.swing.JPanel();
        LabelJudul = new javax.swing.JLabel();
        LabelNama = new javax.swing.JLabel();
        InputBayar = new javax.swing.JTextField();
        LabelBayar = new javax.swing.JLabel();
        InputNama = new javax.swing.JTextField();
        LabelJumlahSpp = new javax.swing.JLabel();
        InputJumlahSPP = new javax.swing.JTextField();
        LabelInfo = new javax.swing.JLabel();
        LabelGaris1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Status = new javax.swing.JLabel();
        LabelGaris2 = new javax.swing.JLabel();
        South = new javax.swing.JPanel();
        HitungPembayaran = new javax.swing.JButton();
        Bayar = new javax.swing.JButton();
        CekStatus = new javax.swing.JButton();
        Keluar = new javax.swing.JButton();
        East = new javax.swing.JPanel();
        Riwayat = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelRiwayat = new javax.swing.JTable();
        Center = new javax.swing.JPanel();
        Januari = new javax.swing.JCheckBox();
        Februari = new javax.swing.JCheckBox();
        Maret = new javax.swing.JCheckBox();
        April = new javax.swing.JCheckBox();
        Mei = new javax.swing.JCheckBox();
        Juni = new javax.swing.JCheckBox();
        Juli = new javax.swing.JCheckBox();
        Agustus = new javax.swing.JCheckBox();
        September = new javax.swing.JCheckBox();
        Oktober = new javax.swing.JCheckBox();
        November = new javax.swing.JCheckBox();
        Desember = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        North.setBackground(new java.awt.Color(255, 255, 204));
        North.setMinimumSize(new java.awt.Dimension(681, 100));
        North.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelJudul.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        LabelJudul.setText("PEMBAYARAN SPP SMK PERSATUAN 1");
        North.add(LabelJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 430, -1));

        LabelNama.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelNama.setText("Nama :");
        North.add(LabelNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 40, -1));

        InputBayar.setEditable(false);
        North.add(InputBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 320, -1));

        LabelBayar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelBayar.setText("Bayar :");
        North.add(LabelBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, 20));
        North.add(InputNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 320, -1));

        LabelJumlahSpp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelJumlahSpp.setText("Jumlah SPP :");
        North.add(LabelJumlahSpp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 20));
        North.add(InputJumlahSPP, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 320, -1));

        LabelInfo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelInfo.setText("*SPP PERBULAN : 500.000");
        North.add(LabelInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 170, -1));

        LabelGaris1.setText("---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");
        North.add(LabelGaris1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, 30));

        jLabel3.setText("Jl. Kepadangan Kebaron Tulangan-Sidoarjo Jawa Timur");
        North.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, -1));

        Status.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Status.setText("Status :");
        North.add(Status, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, -1, -1));

        LabelGaris2.setText("---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");
        North.add(LabelGaris2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, -1, 20));

        getContentPane().add(North, java.awt.BorderLayout.PAGE_START);

        South.setBackground(new java.awt.Color(255, 255, 153));

        HitungPembayaran.setText("Hitung");
        HitungPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungPembayaranActionPerformed(evt);
            }
        });
        South.add(HitungPembayaran);

        Bayar.setText("Bayar");
        Bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BayarActionPerformed(evt);
            }
        });
        South.add(Bayar);

        CekStatus.setText("Cek Status");
        CekStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CekStatusActionPerformed(evt);
            }
        });
        South.add(CekStatus);

        Keluar.setText("Keluar");
        Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarActionPerformed(evt);
            }
        });
        South.add(Keluar);

        getContentPane().add(South, java.awt.BorderLayout.PAGE_END);

        East.setBackground(new java.awt.Color(255, 255, 204));
        East.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Riwayat.setText("Riwayat Pembayaran :");
        East.add(Riwayat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        TabelRiwayat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nama Siswa", "Bulan", "Jumlah SPP"
            }
        ));
        jScrollPane2.setViewportView(TabelRiwayat);

        East.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 16, -1, 77));

        getContentPane().add(East, java.awt.BorderLayout.LINE_END);

        Center.setBackground(new java.awt.Color(255, 255, 204));
        Center.setLayout(new java.awt.GridLayout(3, 4));

        Januari.setText("Januari");
        Center.add(Januari);

        Februari.setText("Februari");
        Center.add(Februari);

        Maret.setText("Maret");
        Center.add(Maret);

        April.setText("April");
        April.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AprilActionPerformed(evt);
            }
        });
        Center.add(April);

        Mei.setText("Mei");
        Center.add(Mei);

        Juni.setText("Juni");
        Center.add(Juni);

        Juli.setText("Juli");
        Juli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JuliActionPerformed(evt);
            }
        });
        Center.add(Juli);

        Agustus.setText("Agustus");
        Center.add(Agustus);

        September.setText("September");
        Center.add(September);

        Oktober.setText("Oktober");
        Center.add(Oktober);

        November.setText("November");
        Center.add(November);

        Desember.setText("Desember");
        Center.add(Desember);

        getContentPane().add(Center, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JuliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JuliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JuliActionPerformed

    private void HitungPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungPembayaranActionPerformed
        // TODO add your handling code here:
        int spp = Integer.parseInt(InputJumlahSPP.getText()); // Jumlah SPP per bulan
        
        if (Januari.isSelected() && !bulan[0]) total += spp;
        if (Februari.isSelected() && !bulan[1]) total += spp;
        if (Maret.isSelected() && !bulan[2]) total += spp;
        if (April.isSelected() && !bulan[3]) total += spp;
        if (Mei.isSelected() && !bulan[4]) total += spp;
        if (Juni.isSelected() && !bulan[5]) total += spp;
        if (Juli.isSelected() && !bulan[6]) total += spp;
        if (Agustus.isSelected() && !bulan[7]) total += spp;
        if (September.isSelected() && !bulan[8]) total += spp;
        if (Oktober.isSelected() && !bulan[9]) total += spp;
        if (November.isSelected() && !bulan[10]) total += spp;
        if (Desember.isSelected() && !bulan[11]) total += spp;
        
        // hasil total pembayaran
        InputBayar.setText(String.valueOf(total));     
        
        JOptionPane.showMessageDialog(this, "Total Pembayaran: Rp " + total);
    }//GEN-LAST:event_HitungPembayaranActionPerformed

    private void BayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BayarActionPerformed
    // TODO add your handling code here:
    String NamaSiswa = InputNama.getText();

    // Validasi atau parsing input yang diharapkan berbentuk angka (misal: jumlah pembayaran)
    double jumlah;
    try {
        jumlah = Double.parseDouble(InputBayar.getText());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Masukkan jumlah pembayaran yang valid.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        return; 
    }

    StringBuilder InfromasiPembayaran = new StringBuilder();

    // Cek tiap bulan dan tambahkan ke log pembayaran jika dipilih dan belum lunas
    if (Januari.isSelected() && !bulan[0]) {
        bulan[0] = true;
        InfromasiPembayaran.append("Januari, ");
    }
    if (Februari.isSelected() && !bulan[1]) {
        bulan[1] = true;
        InfromasiPembayaran.append("Februari, ");
    }
    if (Maret.isSelected() && !bulan[2]) {
        bulan[2] = true;
        InfromasiPembayaran.append("Maret, ");
    }
    if (April.isSelected() && !bulan[3]) {
        bulan[3] = true;
        InfromasiPembayaran.append("April, ");
    }
    if (Mei.isSelected() && !bulan[4]) {
        bulan[4] = true;
        InfromasiPembayaran.append("Mei, ");
    }
    if (Juni.isSelected() && !bulan[5]) {
        bulan[5] = true;
        InfromasiPembayaran.append("Juni, ");
    }
    if (Juli.isSelected() && !bulan[6]) {
        bulan[6] = true;
        InfromasiPembayaran.append("Juli, ");
    }
    if (Agustus.isSelected() && !bulan[7]) {
        bulan[7] = true;
        InfromasiPembayaran.append("Agustus, ");
    }
    if (September.isSelected() && !bulan[8]) {
        bulan[8] = true;
        InfromasiPembayaran.append("September, ");
    }
    if (Oktober.isSelected() && !bulan[9]) {
        bulan[9] = true;
        InfromasiPembayaran.append("Oktober, ");
    }
    if (November.isSelected() && !bulan[10]) {
        bulan[10] = true;
        InfromasiPembayaran.append("November, ");
    }
    if (Desember.isSelected() && !bulan[11]) {
        bulan[11] = true;
        InfromasiPembayaran.append("Desember, ");
    }
    
    // Cek apakah jumlah pembayaran cukup atau berlebihan
    if (jumlah < total) {
        JOptionPane.showMessageDialog(this, "Uang pembayaran tidak cukup! Total Anda : " + total, "PERINGATAN", JOptionPane.ERROR_MESSAGE);
        return;
    } else if (jumlah > total) {
        JOptionPane.showMessageDialog(this, "Masukkan uang pas! Total Anda : " + total, "PERINGATAN", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Tambahkan baris baru ke model tabel
    modelTabel.addRow(new Object[]{NamaSiswa, InfromasiPembayaran.toString(), jumlah});

    JOptionPane.showMessageDialog(this, "Pembayaran berhasil diproses.", "INFORMASI", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_BayarActionPerformed

    private void CekStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CekStatusActionPerformed
        // TODO add your handling code here:
        boolean cekstatus = false;
        StringBuilder status = new StringBuilder("Bulan yang belum dibayar : ");
        // status.setLength(0);
        
        if (!bulan[0]) {
            cekstatus = true;
            status.append("Januari, ");
        }
        if (!bulan[1]) {
            cekstatus = true;
            status.append("Februari, ");
        }
        if (!bulan[2]) {
            cekstatus = true;
            status.append("Maret, ");
        }
        if (!bulan[3]) {
            cekstatus = true;
            status.append("April, ");
        }
        if (!bulan[4]) {
            cekstatus = true;
            status.append("Mei, ");
        }
        if (!bulan[5]) {
            cekstatus = true;
            status.append("Juni, ");
        }
        if (!bulan[6]) {
            cekstatus = true;
            status.append("Juli, ");
        }
        if (!bulan[7]) {
            cekstatus = true;
            status.append("Agustus, ");
        }
        if (!bulan[8]) {
            cekstatus = true;
            status.append("September, ");
        }
        if (!bulan[9]) {
            cekstatus = true;
            status.append("Oktober, ");
        }
        if (!bulan[10]) {
            cekstatus = true;
            status.append("November, ");
        }
        if (!bulan[11]) {
            cekstatus = true;
            status.append("Desember, ");
        }
        
        if (cekstatus) {
            Status.setText("Status : Menunggak");
            JOptionPane.showMessageDialog(this, status.toString());
        } else {
            Status.setText("Status : Lunas");
            JOptionPane.showMessageDialog(this, "Pembayaran Anda Sudah LUNAS", "INFORMASI", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_CekStatusActionPerformed

    private void KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_KeluarActionPerformed

    private void AprilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AprilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AprilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SiswaSindy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SiswaSindy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SiswaSindy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SiswaSindy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SiswaSindy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Agustus;
    private javax.swing.JCheckBox April;
    private javax.swing.JButton Bayar;
    private javax.swing.JButton CekStatus;
    private javax.swing.JPanel Center;
    private javax.swing.JCheckBox Desember;
    private javax.swing.JPanel East;
    private javax.swing.JCheckBox Februari;
    private javax.swing.JButton HitungPembayaran;
    private javax.swing.JTextField InputBayar;
    private javax.swing.JTextField InputJumlahSPP;
    private javax.swing.JTextField InputNama;
    private javax.swing.JCheckBox Januari;
    private javax.swing.JCheckBox Juli;
    private javax.swing.JCheckBox Juni;
    private javax.swing.JButton Keluar;
    private javax.swing.JLabel LabelBayar;
    private javax.swing.JLabel LabelGaris1;
    private javax.swing.JLabel LabelGaris2;
    private javax.swing.JLabel LabelInfo;
    private javax.swing.JLabel LabelJudul;
    private javax.swing.JLabel LabelJumlahSpp;
    private javax.swing.JLabel LabelNama;
    private javax.swing.JCheckBox Maret;
    private javax.swing.JCheckBox Mei;
    private javax.swing.JPanel North;
    private javax.swing.JCheckBox November;
    private javax.swing.JCheckBox Oktober;
    private javax.swing.JLabel Riwayat;
    private javax.swing.JCheckBox September;
    private javax.swing.JPanel South;
    private javax.swing.JLabel Status;
    private javax.swing.JTable TabelRiwayat;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
