/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugas1;

import javax.swing.JOptionPane;

/**
 *
 * @author ZENDIA AMELIA
 */
public class Tampilan1benar extends javax.swing.JFrame {

    /**
     * Creates new form Tampilan1benar
     */
    public Tampilan1benar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Judul1 = new javax.swing.JLabel();
        Judul2 = new javax.swing.JLabel();
        Judul3 = new javax.swing.JLabel();
        Judul4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Nama = new javax.swing.JLabel();
        Tempatlahir = new javax.swing.JLabel();
        Tanggallahir = new javax.swing.JLabel();
        Jeniskelamin = new javax.swing.JLabel();
        Alamat = new javax.swing.JLabel();
        Notelepon = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        Prodi = new javax.swing.JLabel();
        Beasiswa = new javax.swing.JLabel();
        Input1 = new javax.swing.JTextField();
        Input2 = new javax.swing.JTextField();
        Input3 = new javax.swing.JTextField();
        Input4 = new javax.swing.JTextField();
        Input5 = new javax.swing.JTextField();
        Input6 = new javax.swing.JTextField();
        Input7 = new javax.swing.JTextField();
        Lakilaki = new javax.swing.JRadioButton();
        Perempuan = new javax.swing.JRadioButton();
        PilihanBeasiswa = new javax.swing.JComboBox<>();
        Data = new javax.swing.JCheckBox();
        Batal = new javax.swing.JButton();
        Riset = new javax.swing.JButton();
        Simpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        Judul1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Judul1.setText("FORMULIR PENDAFTARAN BEASISWA UTM");
        Judul1.setAlignmentY(10.0F);

        Judul2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Judul2.setText("UNIVERSITAS TRUNOJOYO MADURA");
        Judul2.setAlignmentY(10.0F);

        Judul3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Judul3.setText("Jl. Raya Telang. PO.Box. 2. Kamal, Bangkalan - Madura");

        Judul4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Judul4.setText("Telp : (031) 3011146, Fax. (056) 311109");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tugas1/logo wargalab.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(Judul1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(Judul3))
                            .addComponent(Judul2))
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(Judul4)
                        .addGap(110, 110, 110))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Judul1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Judul2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Judul3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Judul4)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        Nama.setForeground(new java.awt.Color(255, 255, 255));
        Nama.setText("Nama :");

        Tempatlahir.setForeground(new java.awt.Color(255, 255, 255));
        Tempatlahir.setText("Tempat Lahir :");

        Tanggallahir.setForeground(new java.awt.Color(255, 255, 255));
        Tanggallahir.setText("Tanggal Lahir :");

        Jeniskelamin.setForeground(new java.awt.Color(255, 255, 255));
        Jeniskelamin.setText("Jenis Kelamin :");

        Alamat.setForeground(new java.awt.Color(255, 255, 255));
        Alamat.setText("Alamat :");

        Notelepon.setForeground(new java.awt.Color(255, 255, 255));
        Notelepon.setText("No Telepon :");

        Email.setForeground(new java.awt.Color(255, 255, 255));
        Email.setText("Email :");

        Prodi.setForeground(new java.awt.Color(255, 255, 255));
        Prodi.setText("Prodi :");

        Beasiswa.setForeground(new java.awt.Color(255, 255, 255));
        Beasiswa.setText("Beasiswa :");

        Input1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Input1ActionPerformed(evt);
            }
        });

        Input3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Input3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(Lakilaki);
        Lakilaki.setForeground(new java.awt.Color(255, 255, 255));
        Lakilaki.setText("Laki - Laki");
        Lakilaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LakilakiActionPerformed(evt);
            }
        });

        buttonGroup1.add(Perempuan);
        Perempuan.setForeground(new java.awt.Color(255, 255, 255));
        Perempuan.setText("Perempuan");
        Perempuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerempuanActionPerformed(evt);
            }
        });

        PilihanBeasiswa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Beasiswa BSI", "KIP Kuliah", "BeasiswaDjarum", "IBeasiswa Santri", "Beasiswa PPA", "Beasiswa Bank Indonesia" }));

        Data.setForeground(new java.awt.Color(255, 255, 255));
        Data.setText("Data yang saya masukkan sudah benar.");
        Data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataActionPerformed(evt);
            }
        });

        Batal.setText("Batal");
        Batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BatalActionPerformed(evt);
            }
        });

        Riset.setText("Reset");
        Riset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RisetActionPerformed(evt);
            }
        });

        Simpan.setText("Simpan");
        Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Tanggallahir)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Tempatlahir)
                                        .addComponent(Nama))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Alamat)
                                        .addComponent(Jeniskelamin)
                                        .addComponent(Notelepon)
                                        .addComponent(Email)
                                        .addComponent(Prodi)
                                        .addComponent(Beasiswa)))
                                .addGap(57, 57, 57)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Input1)
                                    .addComponent(Input2)
                                    .addComponent(Input3)
                                    .addComponent(Input4)
                                    .addComponent(Input5)
                                    .addComponent(Input6)
                                    .addComponent(Input7)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Lakilaki)
                                        .addGap(26, 26, 26)
                                        .addComponent(Perempuan))
                                    .addComponent(PilihanBeasiswa, 0, 390, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(Data))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(Batal)
                                .addGap(94, 94, 94)
                                .addComponent(Riset)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                                .addComponent(Simpan)
                                .addGap(19, 19, 19)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nama)
                    .addComponent(Input1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tempatlahir)
                    .addComponent(Input2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Tanggallahir)
                    .addComponent(Input3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(Jeniskelamin))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lakilaki)
                            .addComponent(Perempuan))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Alamat)
                    .addComponent(Input4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Notelepon)
                    .addComponent(Input5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Email)
                    .addComponent(Input6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Prodi)
                    .addComponent(Input7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Beasiswa)
                    .addComponent(PilihanBeasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Data)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Batal)
                    .addComponent(Riset)
                    .addComponent(Simpan))
                .addContainerGap(172, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DataActionPerformed

    private void PerempuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerempuanActionPerformed
        // TODO add your handling code here:
        Perempuan.setActionCommand("Perempuan");
    }//GEN-LAST:event_PerempuanActionPerformed

    private void LakilakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LakilakiActionPerformed
        // TODO add your handling code here:
        Lakilaki.setActionCommand("Laki - Laki");
    }//GEN-LAST:event_LakilakiActionPerformed

    private void Input3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Input3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Input3ActionPerformed

    private void Input1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Input1ActionPerformed

    }//GEN-LAST:event_Input1ActionPerformed

    private void SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanActionPerformed
        // TODO add your handling code here:
        Tampilan2 t2 = new Tampilan2();
        if (!Data.isSelected()) {
            JOptionPane.showMessageDialog(null, "Centang Dulu Sebelum Menyimpan!", "PERINGATAN", JOptionPane.WARNING_MESSAGE);
        } else {
            t2.Inputsatu.setText(Input1.getText());
            t2.Inputdua.setText(Input2.getText());
            t2.Inputtiga.setText(Input3.getText());
            if(Lakilaki.isSelected()){
                t2.Inputempat.setText("Laki laki");
            } else{
                t2.Inputempat.setText("Perempuan");
            }
            t2.Inputlima.setText(Input4.getText());
            t2.Inputenam.setText(Input5.getText());
            t2.Inputtujuh.setText(Input6.getText());
            t2.Inputdelapan.setText(Input7.getText());
            String beasiswa = (String)PilihanBeasiswa.getSelectedItem().toString();
            t2.Inputsembilan.setText(beasiswa);
            t2.setVisible(true);
            dispose();
                    
//        String nama = Input1.getText(); 
//        String tempat_lahir = Input2.getText();
//        String tanggal_lahir = Input3.getText();
//        String jenis_kelamin = buttonGroup1.getSelection().getActionCommand();
//        String alamat = Input4.getText();
//        String no_telepon = Input5.getText();
//        String email = Input6.getText();
//        String prodi = Input7.getText(); 
//        String beasiswa = PilihanBeasiswa.getSelectedItem().toString();
//        
//
//        // Tampilkan tampilan baru dan tutup jendela sekarang
//        new Tampilan2(nama, tempat_lahir, tanggal_lahir, jenis_kelamin, alamat, no_telepon, email, prodi, beasiswa).setVisible(true);
//        dispose();
    }

    }//GEN-LAST:event_SimpanActionPerformed

    private void BatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BatalActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BatalActionPerformed

    private void RisetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RisetActionPerformed
        // TODO add your handling code here:
        Input1.setText("");  
        Input2.setText("");  
        Input3.setText("");  
        buttonGroup1.clearSelection();
        Input4.setText("");  
        Input5.setText("");  
        Input6.setText("");  
        Input7.setText(""); 
        PilihanBeasiswa.setSelectedIndex(0);

    }//GEN-LAST:event_RisetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tampilan1benar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tampilan1benar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tampilan1benar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tampilan1benar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tampilan1benar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alamat;
    private javax.swing.JButton Batal;
    private javax.swing.JLabel Beasiswa;
    private javax.swing.JCheckBox Data;
    private javax.swing.JLabel Email;
    private javax.swing.JTextField Input1;
    private javax.swing.JTextField Input2;
    private javax.swing.JTextField Input3;
    private javax.swing.JTextField Input4;
    private javax.swing.JTextField Input5;
    private javax.swing.JTextField Input6;
    private javax.swing.JTextField Input7;
    private javax.swing.JLabel Jeniskelamin;
    private javax.swing.JLabel Judul1;
    private javax.swing.JLabel Judul2;
    private javax.swing.JLabel Judul3;
    private javax.swing.JLabel Judul4;
    private javax.swing.JRadioButton Lakilaki;
    private javax.swing.JLabel Nama;
    private javax.swing.JLabel Notelepon;
    private javax.swing.JRadioButton Perempuan;
    private javax.swing.JComboBox<String> PilihanBeasiswa;
    private javax.swing.JLabel Prodi;
    private javax.swing.JButton Riset;
    private javax.swing.JButton Simpan;
    private javax.swing.JLabel Tanggallahir;
    private javax.swing.JLabel Tempatlahir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
